apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluton-service-capture-chart
  namespace: pluton-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluton-service-capture-chart
  template:
    metadata:
      labels:
        app: pluton-service-capture-chart
    spec:
      containers:
        - name: pluton-service-capture-chart
          image: 905418230863.dkr.ecr.ap-southeast-1.amazonaws.com/ai-agent/pluton-service-capture-chart:c328b64
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pluton-service-capture-chart
  namespace: pluton-dev
spec:
  selector:
    app: pluton-service-capture-chart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
