apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluton-service-capture-chart
  namespace: pluton-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluton-service-capture-chart
  template:
    metadata:
      labels:
        app: pluton-service-capture-chart
    spec:
      containers:
        - name: pluton-service-capture-chart
          image: 905418230863.dkr.ecr.ap-southeast-1.amazonaws.com/ai-agent/pluton-service-capture-chart:2433dff
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: pluton-service-capture-chart-secret
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pluton-service-capture-chart
  namespace: pluton-dev
spec:
  selector:
    app: pluton-service-capture-chart
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
