apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluton-service-gen-account
  namespace: pluton-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluton-service-gen-account
  template:
    metadata:
      labels:
        app: pluton-service-gen-account
    spec:
      containers:
        - name: pluton-service-gen-account
          image: 905418230863.dkr.ecr.ap-southeast-1.amazonaws.com/ai-agent/pluton-service-gen-account:cfcd741
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pluton-service-gen-account
  namespace: pluton-dev
spec:
  selector:
    app: pluton-service-gen-account
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
