apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluton-service-jupiter
  namespace: pluton-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluton-service-jupiter
  template:
    metadata:
      labels:
        app: pluton-service-jupiter
    spec:
      containers:
        - name: pluton-service-jupiter
          image: 905418230863.dkr.ecr.ap-southeast-1.amazonaws.com/ai-agent/pluton-service-jupiter:d8f6a8e
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pluton-service-jupiter
  namespace: pluton-dev
spec:
  selector:
    app: pluton-service-jupiter
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
