apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluton-client
  namespace: pluton-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluton-client
  template:
    metadata:
      labels:
        app: pluton-client
    spec:
      containers:
        - name: pluton-client
          image: 905418230863.dkr.ecr.ap-southeast-1.amazonaws.com/ai-agent/pluton-client:v1.14
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pluton-client
  namespace: pluton-dev
spec:
  selector:
    app: pluton-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pluton-ingress
  namespace: pluton-dev
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - beta.plutonai.fun
      secretName: tls-pluton-client
  rules:
    - host: beta.plutonai.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pluton-client
                port:
                  number: 3000
