apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluton-client
  namespace: pluton-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluton-client
  template:
    metadata:
      labels:
        app: pluton-client
    spec:
      containers:
        - name: pluton-client
          image: 905418230863.dkr.ecr.ap-southeast-1.amazonaws.com/ai-agent/pluton-client:8d88ded
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: pluton-client-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pluton-client
  namespace: pluton-dev
spec:
  selector:
    app: pluton-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
