apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pluton-landing-ingress
  namespace: pluton-dev
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - plutonai.fun
      secretName: tls-pluton-landing
  rules:
    - host: plutonai.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pluton-landing
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pluton-app-ingress
  namespace: pluton-dev
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.plutonai.fun
      secretName: tls-pluton-app
  rules:
    - host: app.plutonai.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pluton-client
                port:
                  number: 3000
